{% set name = "syntheseus" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/syntheseus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2afdd17dc9ab5cd284443c7612b0c2350847fc7988013bb1ca7b236222c54683

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - networkx
    - numpy
    - python >=3.7
    - rdkit

test:
  imports:
    - syntheseus
    - syntheseus.interface
    - syntheseus.search

about:
  home: https://github.com/microsoft/syntheseus
  summary: Benchmarking Chemical Synthesis Planning Algorithms
  description: |
    Syntheseus is a package for retrosynthetic planning. It contains implementations
    of common search algorithms and a simple API to wrap custom reaction models and
    write custom algorithms. It is meant to allow for simple benchmarking of
    the components of retrosynthesis algorithms.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
