{% set name = "syntheseus" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}-pkg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/syntheseus-{{ version }}.tar.gz
  sha256: 7fa92d69e1eac66b431e451ca2434f778ab8d1b9fb52eea8e9bb4eba21ecc7f6

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build-pkg.sh
    build:
      noarch: python
      entry_points:
        - {{ name }} = {{ name }}.cli.main:main

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=45
        - setuptools-scm >=6.2
      run:
        - networkx
        - numpy
        - more-itertools
        - omegaconf
        - python >={{ python_min }}
        - rdkit
        - tqdm

    test:
      requires:
        - python {{ python_min }}
      commands:
        - command -v syntheseus
      imports:
        - syntheseus
        - syntheseus.interface
        - syntheseus.search

  - name: {{ name }}-viz
    build:
      noarch: generic
    requirements:
      run:
        - {{ name }} =={{ version }}
        - pillow
        - python-graphviz

    test:
      commands:
        - command -v syntheseus
      imports:
        - syntheseus
        - syntheseus.interface
        - syntheseus.search

about:
  home: https://github.com/microsoft/syntheseus
  summary: Benchmarking Chemical Synthesis Planning Algorithms
  description: |
    Syntheseus is a package for retrosynthetic planning. It contains implementations
    of common search algorithms and a simple API to wrap custom reaction models and
    write custom algorithms. It is meant to allow for simple benchmarking of
    the components of retrosynthesis algorithms.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
